from pathlib import Path
p=Path(r'C:\Users\email\Documents\GitHub\Juice-Labs\rgpu\proxy-d3d12\src\rgpu_dxgi_early.cpp')
s=p.read_text(encoding='utf-8').replace('\r\n','\n')
old='''static HRESULT WINAPI hook_core_get_interface(REFCLSID clsid, REFIID riid, void **ppv) {\n    InterlockedIncrement(&g_core_get_interface_calls);\n    HRESULT hr = g_core_get_interface_original(clsid, riid, ppv);\n    void *obj = (SUCCEEDED(hr) && ppv) ? *ppv : nullptr;\n    log_line("D3D12Core!D3D12GetInterface clsid={%08lX-%04X-%04X-...} iid={%08lX-%04X-%04X-...} hr=0x%08lX object=%p",\n             (unsigned long)clsid.Data1, (unsigned)clsid.Data2, (unsigned)clsid.Data3,\n             (unsigned long)riid.Data1, (unsigned)riid.Data2, (unsigned)riid.Data3,\n             (unsigned long)hr, obj);\n'''
new='''static HRESULT WINAPI hook_core_get_interface(REFCLSID clsid, REFIID riid, void **ppv) {\n    InterlockedIncrement(&g_core_get_interface_calls);\n    void *returnAddress = __builtin_return_address(0);\n    HRESULT hr = g_core_get_interface_original(clsid, riid, ppv);\n    void *obj = (SUCCEEDED(hr) && ppv) ? *ppv : nullptr;\n    char callerDesc[320]; describe_address(returnAddress, callerDesc, sizeof(callerDesc));\n    log_line("D3D12Core!D3D12GetInterface caller=%p %s clsid={%08lX-%04X-%04X-...} iid={%08lX-%04X-%04X-...} hr=0x%08lX object=%p",\n             returnAddress, callerDesc,\n             (unsigned long)clsid.Data1, (unsigned)clsid.Data2, (unsigned)clsid.Data3,\n             (unsigned long)riid.Data1, (unsigned)riid.Data2, (unsigned)riid.Data3,\n             (unsigned long)hr, obj);\n    if (obj && riid.Data1 == 0xDFAFDD2C) {\n        void **vt = *(void ***)obj;\n        for (unsigned i = 0; i < 9; ++i) {\n            char desc[320]; describe_address(vt[i], desc, sizeof(desc));\n            log_line("COREMODULE_VTBL[%u]=%p %s", i, vt[i], desc);\n        }\n    }\n'''
if s.count(old)!=1: raise RuntimeError(f'getinterface block matches={s.count(old)}')
s=s.replace(old,new,1)
p.write_text(s.replace('\n','\r\n'),encoding='utf-8',newline='')
print('Added D3D12Core caller and CoreModule vtable diagnostics.')
