from pathlib import Path
p=Path(r'C:\Users\email\Documents\GitHub\Juice-Labs\rgpu\proxy-d3d12\src\rgpu_dxgi_early.cpp')
s=p.read_text(encoding='utf-8').replace('\r\n','\n')

old='''typedef HRESULT (WINAPI *fnCoreGetInterface)(REFCLSID, REFIID, void **);\ntypedef HRESULT (STDMETHODCALLTYPE *fnCoreGetDllExports)(IUnknown *, void *);\n'''
new='''typedef HRESULT (WINAPI *fnCoreGetInterface)(REFCLSID, REFIID, void **);\ntypedef HRESULT (WINAPI *fnSystemD3D12CreateDevice)(IUnknown *, D3D_FEATURE_LEVEL, REFIID, void **);\ntypedef HRESULT (STDMETHODCALLTYPE *fnCoreGetDllExports)(IUnknown *, void *);\n'''
if s.count(old)!=1: raise RuntimeError('typedef point missing')
s=s.replace(old,new,1)

old='''static fnCoreGetInterface g_core_get_interface_original = nullptr;\nstatic fnCoreGetDllExports g_core_get_dll_exports_original = nullptr;\n'''
new='''static fnCoreGetInterface g_core_get_interface_original = nullptr;\nstatic fnSystemD3D12CreateDevice g_system_create_device_original = nullptr;\nstatic void *g_system_create_device_target = nullptr;\nstatic volatile LONG g_system_create_hook_installed = 0;\nstatic volatile LONG g_system_create_calls = 0;\nstatic volatile LONG g_system_create_devices = 0;\nstatic fnCoreGetDllExports g_core_get_dll_exports_original = nullptr;\n'''
if s.count(old)!=1: raise RuntimeError('globals point missing')
s=s.replace(old,new,1)

old='''static void arm_device(ID3D12Device *device, const char *source) {\n    if (!device) return;\n    fnArmExternalDevice arm = find_arm_export(true);\n    if (arm) {\n        arm(device, source);\n        InterlockedIncrement(&g_arm_calls);\n        log_line("%s returned device handed to rgpu D3D12 capture device=%p", source, (void *)device);\n    } else {\n        log_line("%s returned device but rgpu_d3d12_arm_external_device was not found", source);\n    }\n}\n\nstatic bool patch_slot'''
new='''static void arm_device(ID3D12Device *device, const char *source) {\n    if (!device) return;\n    fnArmExternalDevice arm = find_arm_export(true);\n    if (arm) {\n        arm(device, source);\n        InterlockedIncrement(&g_arm_calls);\n        log_line("%s returned device handed to rgpu D3D12 capture device=%p", source, (void *)device);\n    } else {\n        log_line("%s returned device but rgpu_d3d12_arm_external_device was not found", source);\n    }\n}\n\nstatic HRESULT WINAPI hook_system_d3d12_create_device(\n    IUnknown *adapter, D3D_FEATURE_LEVEL featureLevel, REFIID riid, void **ppDevice) {\n    InterlockedIncrement(&g_system_create_calls);\n    HRESULT hr = g_system_create_device_original(adapter, featureLevel, riid, ppDevice);\n    ID3D12Device *device = (SUCCEEDED(hr) && ppDevice) ? (ID3D12Device *)*ppDevice : nullptr;\n    log_line("SYSTEM d3d12!D3D12CreateDevice iid={%08lX-%04X-%04X-...} fl=0x%X hr=0x%08lX device=%p vtbl=%p",\n             (unsigned long)riid.Data1, (unsigned)riid.Data2, (unsigned)riid.Data3,\n             (unsigned)featureLevel, (unsigned long)hr, (void *)device,\n             device ? *(void **)device : nullptr);\n    if (device) {\n        InterlockedIncrement(&g_system_create_devices);\n        arm_device(device, "System_D3D12CreateDevice");\n    }\n    return hr;\n}\n\nstatic bool hook_system_d3d12_module(HMODULE module) {\n    if (!module || g_system_create_hook_installed) return g_system_create_hook_installed != 0;\n    if (GetProcAddress(module, "rgpu_d3d12_arm_external_device"))\n        return false; /* our game-directory proxy, not the system runtime */\n    FARPROC target = GetProcAddress(module, "D3D12CreateDevice");\n    if (!target) return false;\n    void *trampoline = nullptr;\n    if (!rgpu_inline_hook((void *)target, (void *)hook_system_d3d12_create_device, &trampoline)) {\n        g_system_create_device_target = (void *)target;\n        return false;\n    }\n    g_system_create_device_target = (void *)target;\n    g_system_create_device_original = reinterpret_cast<fnSystemD3D12CreateDevice>(trampoline);\n    InterlockedExchange(&g_system_create_hook_installed, 1);\n    return true;\n}\n\nstatic bool patch_slot'''
if s.count(old)!=1: raise RuntimeError('arm insertion point missing')
s=s.replace(old,new,1)

old='''    if (reason == 1 && data &&\n        unicode_equals_ci(data->Loaded.BaseDllName, L"D3D12Core.dll")) {\n        /* Loader-lock callback: only GetProcAddress + VirtualAlloc/Protect based\n         * hook installation. Logging is deferred to a normal worker thread. */\n        hook_d3d12core_module((HMODULE)data->Loaded.DllBase);\n    }\n'''
new='''    if (reason == 1 && data) {\n        /* Loader-lock callback: only GetProcAddress + VirtualAlloc/Protect based\n         * hook installation. Logging is deferred to a normal worker thread. */\n        if (unicode_equals_ci(data->Loaded.BaseDllName, L"D3D12Core.dll"))\n            hook_d3d12core_module((HMODULE)data->Loaded.DllBase);\n        if (unicode_equals_ci(data->Loaded.BaseDllName, L"d3d12.dll"))\n            hook_system_d3d12_module((HMODULE)data->Loaded.DllBase);\n    }\n'''
if s.count(old)!=1: raise RuntimeError('notification block missing')
s=s.replace(old,new,1)

old='''static DWORD WINAPI core_monitor_thread(void *) {\n    for (int i = 0; i < 200; ++i) {\n        HMODULE core = GetModuleHandleW(L"D3D12Core.dll");\n        if (core) {\n            hook_d3d12core_module(core);\n            log_line("D3D12Core monitor module=%p target=%p hook=%ld calls=%ld",\n                     (void *)core, g_core_target, g_core_hook_installed,\n                     g_core_get_interface_calls);\n            return 0;\n        }\n        Sleep(50);\n    }\n    log_line("D3D12Core monitor timed out before module load");\n    return 0;\n}\n'''
new='''static DWORD WINAPI core_monitor_thread(void *) {\n    for (int i = 0; i < 200; ++i) {\n        HMODULE core = GetModuleHandleW(L"D3D12Core.dll");\n        if (core) hook_d3d12core_module(core);\n\n        /* Enumerate all modules because Windows can load both the game-directory\n         * d3d12 proxy and the real System32 d3d12.dll under the same base name. */\n        HANDLE snap = CreateToolhelp32Snapshot(TH32CS_SNAPMODULE | TH32CS_SNAPMODULE32,\n                                               GetCurrentProcessId());\n        if (snap != INVALID_HANDLE_VALUE) {\n            MODULEENTRY32 me{}; me.dwSize = sizeof(me);\n            if (Module32First(snap, &me)) do {\n                if (_wcsicmp(me.szModule, L"d3d12.dll") == 0)\n                    hook_system_d3d12_module(me.hModule);\n            } while (Module32Next(snap, &me));\n            CloseHandle(snap);\n        }\n\n        if (core && g_core_hook_installed && g_system_create_hook_installed) {\n            log_line("runtime monitor Core=%p CoreTarget=%p CoreHook=%ld CoreCalls=%ld SystemCreateTarget=%p SystemHook=%ld SystemCalls=%ld Devices=%ld",\n                     (void *)core, g_core_target, g_core_hook_installed,\n                     g_core_get_interface_calls, g_system_create_device_target,\n                     g_system_create_hook_installed, g_system_create_calls,\n                     g_system_create_devices);\n            return 0;\n        }\n        Sleep(50);\n    }\n    log_line("runtime monitor timeout CoreHook=%ld SystemHook=%ld",\n             g_core_hook_installed, g_system_create_hook_installed);\n    return 0;\n}\n'''
if s.count(old)!=1: raise RuntimeError('monitor block missing')
s=s.replace(old,new,1)

old='''    if (factoryDeviceCalls) *factoryDeviceCalls = g_factory_device_calls;\n}\n'''
new='''    if (factoryDeviceCalls) *factoryDeviceCalls = g_factory_device_calls;\n}\n__declspec(dllexport) void WINAPI rgpu_dxgi_system_create_stats(\n    long *installed, long *calls, long *devices) {\n    if (installed) *installed = g_system_create_hook_installed;\n    if (calls) *calls = g_system_create_calls;\n    if (devices) *devices = g_system_create_devices;\n}\n'''
if s.count(old)!=1: raise RuntimeError('stats point missing')
s=s.replace(old,new,1)

p.write_text(s.replace('\n','\r\n'),encoding='utf-8',newline='')
print('Added global system d3d12!D3D12CreateDevice inline interception.')
