from pathlib import Path
p = Path(r'C:\Users\email\Documents\GitHub\Juice-Labs\rgpu\proxy-d3d12\src\rgpu_d3d12_proxy.cpp')
s = p.read_text(encoding='utf-8').replace('\r\n','\n')
old = '''    install_batch_frozen(items, n);\n\n    rgpu_log("armed-inline %s device input=%p base=%p/vtbl=%p d4=%p/vtbl=%p d9=%p/vtbl=%p originals CFS=%p CCQ=%p CCL=%p CCQ1=%p CCL1=%p",\n             which, (void *)dev, (void *)base, bv, (void *)d4, v4, (void *)d9, v9,\n             (void *)o_CFS, (void *)o_DevCCQ, (void *)o_DevCCL,\n             (void *)o_DevCCQ1, (void *)o_DevCCL1);\n'''
new = '''    install_batch_frozen(items, n);\n\n    /* The conservative inline decoder can reject some base-method prologues.\n     * Keep a safe vtable fallback for those exact methods; the Agility 1 methods\n     * remain inline-hooked and therefore survive later overlay vtable changes. */\n    bool fbCFS = false, fbCCQ = false, fbCCL = false, fbCCQ1 = false, fbCCL1 = false;\n    if (base && !o_CFS) fbCFS = patch_slot(base, RGPU_SLOT_Device_CheckFeatureSupport,\n                                            (void *)h_CFS, (void **)&o_CFS);\n    if (base && !o_DevCCQ) fbCCQ = patch_slot(base, RGPU_SLOT_Device_CreateCommandQueue,\n                                              (void *)h_DevCCQ, (void **)&o_DevCCQ);\n    if (base && !o_DevCCL) fbCCL = patch_slot(base, RGPU_SLOT_Device_CreateCommandList,\n                                              (void *)h_DevCCL, (void **)&o_DevCCL);\n    if (d9 && !o_DevCCQ1) fbCCQ1 = patch_slot(d9, RGPU_SLOT_Device9_CreateCommandQueue1,\n                                               (void *)h_DevCCQ1, (void **)&o_DevCCQ1);\n    if (d4 && !o_DevCCL1) fbCCL1 = patch_slot(d4, RGPU_SLOT_Device4_CreateCommandList1,\n                                               (void *)h_DevCCL1, (void **)&o_DevCCL1);\n\n    rgpu_log("armed-hybrid %s device input=%p base=%p/vtbl=%p d4=%p/vtbl=%p d9=%p/vtbl=%p originals CFS=%p CCQ=%p CCL=%p CCQ1=%p CCL1=%p fallback=%d/%d/%d/%d/%d",\n             which, (void *)dev, (void *)base, bv, (void *)d4, v4, (void *)d9, v9,\n             (void *)o_CFS, (void *)o_DevCCQ, (void *)o_DevCCL,\n             (void *)o_DevCCQ1, (void *)o_DevCCL1,\n             fbCFS, fbCCQ, fbCCL, fbCCQ1, fbCCL1);\n'''
if s.count(old) != 1:
    raise RuntimeError(f'Expected one inline-arm logging block, found {s.count(old)}')
s = s.replace(old,new,1)
p.write_text(s.replace('\n','\r\n'), encoding='utf-8', newline='')
print('Added vtable fallback for device methods whose inline prologues are rejected.')
