from pathlib import Path
p=Path(r'C:\Users\email\Documents\GitHub\Juice-Labs\rgpu\proxy-d3d12\test_txr_ags_early_live.ps1')
s=p.read_text(encoding='utf-8').replace('\r\n','\n')
s=s.replace('''    ags_device_armed = $false\n    command_stream_live = $false\n''','''    ags_device_armed = $false\n    core_hook_installed = $false\n    core_getinterface_intercepted = $false\n    core_device_armed = $false\n    command_stream_live = $false\n''')
s=s.replace('''        arm_missing = 'arm_external_device export was not found'\n''','''        arm_missing = 'arm_external_device export was not found'\n        core_monitor = 'D3D12Core monitor module='\n        core_hook_yes = 'D3D12Core monitor module='\n        core_getinterface = 'D3D12Core!D3D12GetInterface clsid='\n        core_sdk_factory = 'D3D12Core SDKConfiguration1::CreateDeviceFactory'\n        core_factory_device = 'D3D12Core DeviceFactory::CreateDevice'\n        core_handed = 'D3D12Core_DeviceFactory returned device handed to rgpu D3D12 capture'\n''')
s=s.replace('''        armed_ags = 'armed-hybrid AMD_AGS device'\n''','''        armed_ags = 'armed-hybrid AMD_AGS device'\n        external_core_arm = 'external device arm source=D3D12Core_DeviceFactory'\n        armed_core = 'armed-hybrid D3D12Core_DeviceFactory device'\n''')
s=s.replace('''    $report.ags_device_armed = ($report.dxgi_markers.handed -gt 0 -and $report.d3d12_markers.external_ags_arm -gt 0)\n    $report.command_stream_live = (\n''','''    $report.ags_device_armed = ($report.dxgi_markers.handed -gt 0 -and $report.d3d12_markers.external_ags_arm -gt 0)\n    $report.core_hook_installed = ($dxgiLog -match 'D3D12Core monitor module=.*hook=1')\n    $report.core_getinterface_intercepted = $report.dxgi_markers.core_getinterface -gt 0\n    $report.core_device_armed = ($report.dxgi_markers.core_handed -gt 0 -and $report.d3d12_markers.external_core_arm -gt 0)\n    $report.command_stream_live = (\n''')
p.write_text(s.replace('\n','\r\n'),encoding='utf-8',newline='')
print('Added D3D12Core interception markers to bounded TXR live test.')
