from pathlib import Path
p=Path(r'C:\Users\email\Documents\GitHub\Juice-Labs\rgpu\proxy-d3d12\test\rgpu_ags_early_harness.cpp')
s=p.read_text(encoding='utf-8').replace('\r\n','\n')
s=s.replace('typedef void (WINAPI *pSystemStats)(long *, long *, long *);',
'''typedef void (WINAPI *pSystemStats)(long *, long *, long *);\ntypedef void (WINAPI *pCoreTableStats)(long *, long *);''')
s=s.replace('''    pSystemStats systemStats = (pSystemStats)GetProcAddress(dxgi, "rgpu_dxgi_system_create_stats");\n    if (!install || !stats || !systemStats) { std::printf("FAIL: early DXGI exports missing\\n"); return 1; }\n''','''    pSystemStats systemStats = (pSystemStats)GetProcAddress(dxgi, "rgpu_dxgi_system_create_stats");\n    pCoreTableStats coreTableStats = (pCoreTableStats)GetProcAddress(dxgi, "rgpu_dxgi_core_table_create_stats");\n    if (!install || !stats || !systemStats || !coreTableStats) { std::printf("FAIL: early DXGI exports missing\\n"); return 1; }\n''')
s=s.replace('''    long systemInstalled=0, systemCalls=0, systemDevices=0;\n    systemStats(&systemInstalled, &systemCalls, &systemDevices);\n    std::printf("AGS rc=%d device=%p | AGS hook=%ld calls=%ld | system hook=%ld calls=%ld devices=%ld | external-arms=%ld | core-hook=%ld core-calls=%ld\\n",\n                rc, (void *)rp.pDevice, installed, calls, systemInstalled, systemCalls, systemDevices,\n                arms, coreInstalled, coreCalls);\n\n    bool ok = rc == 0 && rp.pDevice && installed == 1 && calls == 1 &&\n              systemInstalled == 1 && systemCalls >= 1 && systemDevices >= 1 && arms >= 2;\n''','''    long systemInstalled=0, systemCalls=0, systemDevices=0;\n    long coreTableCalls=0, coreTableDevices=0;\n    systemStats(&systemInstalled, &systemCalls, &systemDevices);\n    coreTableStats(&coreTableCalls, &coreTableDevices);\n    std::printf("AGS rc=%d device=%p | AGS hook=%ld calls=%ld | system hook=%ld calls=%ld devices=%ld | Core table calls=%ld devices=%ld | external-arms=%ld | core-hook=%ld core-calls=%ld\\n",\n                rc, (void *)rp.pDevice, installed, calls, systemInstalled, systemCalls, systemDevices,\n                coreTableCalls, coreTableDevices, arms, coreInstalled, coreCalls);\n\n    bool ok = rc == 0 && rp.pDevice && installed == 1 && calls == 1 &&\n              systemInstalled == 1 && systemCalls >= 1 && systemDevices >= 1 &&\n              coreTableCalls >= 1 && coreTableDevices >= 1 && arms >= 3;\n''')
p.write_text(s.replace('\n','\r\n'),encoding='utf-8',newline='')
print('Harness now requires Core dispatch-table CreateDevice interception.')
