from pathlib import Path
p=Path(r'C:\Users\email\Documents\GitHub\Juice-Labs\rgpu\proxy-d3d12\test\rgpu_ags_early_harness.cpp')
s=p.read_text(encoding='utf-8').replace('\r\n','\n')
s=s.replace('typedef void (WINAPI *pEarlyStats)(long *, long *, long *, long *, long *, long *, long *);',
'''typedef void (WINAPI *pEarlyStats)(long *, long *, long *, long *, long *, long *, long *);\ntypedef void (WINAPI *pSystemStats)(long *, long *, long *);''')
s=s.replace('''    pEarlyStats stats = (pEarlyStats)GetProcAddress(dxgi, "rgpu_dxgi_early_stats");\n    if (!install || !stats) { std::printf("FAIL: early DXGI exports missing\\n"); return 1; }\n''','''    pEarlyStats stats = (pEarlyStats)GetProcAddress(dxgi, "rgpu_dxgi_early_stats");\n    pSystemStats systemStats = (pSystemStats)GetProcAddress(dxgi, "rgpu_dxgi_system_create_stats");\n    if (!install || !stats || !systemStats) { std::printf("FAIL: early DXGI exports missing\\n"); return 1; }\n''')
s=s.replace('''    std::printf("AGS rc=%d device=%p | hook=%ld calls=%ld external-arms=%ld | core-hook=%ld core-calls=%ld\\n",\n                rc, (void *)rp.pDevice, installed, calls, arms, coreInstalled, coreCalls);\n\n    bool ok = rc == 0 && rp.pDevice && installed == 1 && calls == 1 && arms == 1;\n''','''    long systemInstalled=0, systemCalls=0, systemDevices=0;\n    systemStats(&systemInstalled, &systemCalls, &systemDevices);\n    std::printf("AGS rc=%d device=%p | AGS hook=%ld calls=%ld | system hook=%ld calls=%ld devices=%ld | external-arms=%ld | core-hook=%ld core-calls=%ld\\n",\n                rc, (void *)rp.pDevice, installed, calls, systemInstalled, systemCalls, systemDevices,\n                arms, coreInstalled, coreCalls);\n\n    bool ok = rc == 0 && rp.pDevice && installed == 1 && calls == 1 &&\n              systemInstalled == 1 && systemCalls >= 1 && systemDevices >= 1 && arms >= 2;\n''')
p.write_text(s.replace('\n','\r\n'),encoding='utf-8',newline='')
print('Updated harness to require AGS and global system D3D12 interception.')
